// <auto-generated />
namespace MoiGiangApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddNamHoc_HocKy_Nganh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNamHoc_HocKy_Nganh));
        
        string IMigrationMetadata.Id
        {
            get { return "202511071843385_AddNamHoc_HocKy_Nganh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
